name: ios_gallery_app
description: A Flutter gallery app with iOS-like interface for viewing photos and videos

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.6
  
  # State Management
  provider: ^6.1.1
  
  # Media handling
  photo_manager: ^3.0.0
  video_player: ^2.8.1
  cached_network_image: ^3.3.0
  
  # File handling
  path_provider: ^2.1.1
  
  # Utilities
  collection: ^1.18.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"