name: ios_gallery_app
description: A Flutter gallery app with iOS-like interface for viewing photos and videos

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.2
  
  # State Management
  provider: ^6.0.5
  
  # Media handling
  photo_manager: ^2.7.1
  video_player: ^2.7.0
  cached_network_image: ^3.2.3
  
  # File handling
  path_provider: ^2.0.15
  
  # Utilities
  collection: ^1.17.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"